name: "Release Lineaje"
on:
  workflow_dispatch:
    inputs:
      version:
        description: provide the tag to build and release (prefixed with v)
        required: true

permissions:
  contents: read

jobs:
  quality-gate:
    environment: release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - name: Check if tag already exists
        # note: this will fail if the tag does not exist
        run: |
            [[ "${{ github.event.inputs.version }}" == v* ]] || (echo "version '${{ github.event.inputs.version }}' does not have a 'v' prefix" && exit 1)
            if git show-ref --tags --verify --quiet "refs/tags/${{ github.event.inputs.version }}"; then
              echo "Tag ${{ github.event.inputs.version }} exists"
            else
              echo "Tag ${{ github.event.inputs.version }} does not exist"
            fi

      - name: Checkout tag
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          ref: "${{ github.event.inputs.version }}"

      - name: Check if pinned syft is a release version
        run: .github/scripts/check-syft-version-is-release.sh

  # only release core assets within the "release" job. Any other assets not already under the purview of the
  # goreleaser configuration should be added as separate jobs to allow for debugging separately from the release workflow
  # as well as not accidentally be re-run as a step multiple times (as could be done within the release workflow) as
  # not all actions are guaranteed to be idempotent.
  release:
    needs: [quality-gate]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap
        with:
          # use the same cache we used for building snapshots
          build-cache-key-prefix: "snapshot"

      - name: Build & publish release artifacts
        run: make ci-release
        env:
          # for creating the release (requires write access to packages and content)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: anchore/sbom-action@e11c554f704a0b820cbf8c51673f6945e0731532 # v0.20.0
        continue-on-error: true
        with:
          artifact-name: sbom.spdx.json

